dataset:
  key: 'Planetoid'
  init:
    kwargs:
      name: &dataset_name 'cora'
      root: &root_dir !join ['./resource/dataset/', *dataset_name]

models:
  teacher_model:
    key: 'GCNModel'
    kwargs:
      feature_dim: 1433
      hidden_dim: 256
      num_class: 7
    src_ckpt:
    dst_ckpt: !join ['./resource/ckpt/', *dataset_name, 'teacher_model.pt']

  student_model:
    key: 'test_gcn'
    kwargs:
      in_channels: 1433
      out_channels: 7
    src_ckpt:
    dst_ckpt: !join ['./resource/ckpt/', *dataset_name, 'student_model.pt']

train:
  num_epochs: 182
  # sampler: 'NeighborSampler'
  #     edge_index: *dataset.edge_index
  #     node_idx: [0, 8, 45, 33]
  #     sample_list: [2, 8]
  #     batch_size: 2048
  #     shuffle: True
  #     num_workers: 0
  train_data_loader:
    kwargs:
      dataset: *dataset_name
      batch_size: 128
      shuffle: False
  model:
    forward_proc: 'forward_batch_only'
  teacher:
    forward_proc: 'forward_batch_only'
    requires_grad: False
  student:
    forward_proc: 'forward_batch_only'
    requires_grad: True
  optimizer:
    key: 'Adam'
    kwargs:
      lr: 0.1
      weight_decay: 0.0001
  scheduler:
    key: 'MultiStepLR'
    kwargs:
      # learning_rate: 0.01
      milestones: [91, 136]
      gamma: 0.1
  criterion:
    key: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        kd:
          criterion:
            key: 'KDLoss'
            kwargs:
              student_module_path: '.'
              student_module_io: 'output'
              teacher_module_path: '.'
              teacher_module_io: 'output'
              temperature: 4.0
              alpha: 0.9
              reduction: 'batchmean'
          weight: 1.0
test: