dataset:
  key: 'Planetoid'
  init:
    kwargs:
      name: &dataset_name 'cora'
      root: &root_dir !join ['./resource/dataset/', *dataset_name]

models:
  teacher_model:
    key: 'GCNModel'
    kwargs:
      feature_dim: 1433
      hidden_dim: 256
      num_class: 7
    src_ckpt: !join ['./resource/ckpt/', *dataset_name, '-teacher_model.npz']
    # dst_ckpt: !join ['./resource/ckpt/', *dataset_name, '-teacher_model.pt']

  student_model:
    key: 'GCNModel'
    common_args:
      feature_dim: 1433
      hidden_dim: 256
      num_class: 7
    src_ckpt: !join ['./resource/ckpt/', *dataset_name, '-student_model.npz']
    dst_ckpt: !join ['./resource/ckpt/', *dataset_name, '-student_model.npz']

train:
  log_freq: 10
  num_epochs: 182
  use_dataloader: False
  # sampler: 'NeighborSampler'
  #     edge_index: *dataset.edge_index
  #     node_idx: [0, 8, 45, 33]
  #     sample_list: [2, 8]
  #     batch_size: 2048
  #     shuffle: True
  #     num_workers: 0
  train_data_loader:
    split: 'train'
    kwargs:
      batch_size: 128
      shuffle: False
  test_data_loader:
    split: 'test'
    kwargs:
      batch_size: 128
      shuffle: False
  val_data_loader:
    split: 'val'
    kwargs:
      batch_size: 128
      shuffle: False
  model:
    forward_proc: 'forward_all'
    # forward_proc: 'forward_batch_only'
  teacher:
    forward_proc: 'forward_all'
    requires_grad: False
  student:
    forward_proc: 'forward_all'
    requires_grad: True
  optimizer:
    key: 'Adam'
    kwargs:
      lr: 0.1
      weight_decay: 0.0001
  scheduler:
    key: 'MultiStepDecay'
    kwargs:
      # learning_rate: 0.01
      milestones: [91, 136]
      gamma: 0.1
  criterion:
    key: 'glnn_loss_func'
    kwargs:
      loss_fn: 'softmax_cross_entropy_with_logits'